check branch protection

diff --git a/.github/workflows/files-presence-validation.yml b/.github/workflows/files-presence-validation.yml
--- a/.github/workflows/files-presence-validation.yml
+++ b/.github/workflows/files-presence-validation.yml
@@ -48,3 +48,15 @@ jobs:
         fi
       if: always()
       shell: bash
+
+    - name: Check if main branch is protected
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        protection=$(curl -H "Authorization: token $GITHUB_TOKEN" -s "https://api.github.com/repos/${{ github.repository }}/branches/main/protection")
+        if [[ "$protection" == "Not Found" ]]; then
+          echo "Error: The main branch is not protected!" >&2
+          exit 1
+        fi
+      if: always()
+      shell: bash
